Remove 3.4, head ruby versions due to nokogiri conflict
https://github.com/lekemula/solargraph-rspec/actions/runs/14009796421/job/39228155930?pr=8

nokogiri-1.17.2-x86_64-linux requires ruby version < 3.4.dev, >= 3.0,
which is
incompatible with the current version, ruby 3.5.0p-1
Error: Process completed with exit code 5.