Require ruby >=3 and update gems (#8)
* Require ruby >=3 and update gems

See: https://github.com/castwide/solargraph/pull/791

* Fix specs

* Update ruby versions CI matrix

* Remove 3.4, head ruby versions due to nokogiri conflict

https://github.com/lekemula/solargraph-rspec/actions/runs/14009796421/job/39228155930?pr=8

nokogiri-1.17.2-x86_64-linux requires ruby version < 3.4.dev, >= 3.0,
which is
incompatible with the current version, ruby 3.5.0p-1
Error: Process completed with exit code 5.

* Clean appraisals

Keeping the gem because it might be useful in the future.

* Fix new rubocop failures

* Remove Solargraph::Parser.rubyvm? references